# Generated by Django 5.2.12 on 2026-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_embedding_alter_stock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=150)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('discount_from_52w_high', models.FloatField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(default='Neutral', max_length=20)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('revenue_growth', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
